# Generated by Django 5.2.1 on 2025-05-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0009_remove_product_product_category_delete_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.PositiveIntegerField()),
                ('cart_total_amount', models.PositiveIntegerField()),
                ('cart_created_date', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField()),
                ('p_photo', models.ImageField(upload_to='product')),
                ('p_price', models.PositiveIntegerField()),
                ('p_dis_pirce', models.PositiveIntegerField(default=0)),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
