# Generated by Django 5.2.1 on 2025-05-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_cart_cart_product_remove_cart_cart_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cart_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
        ),
    ]
